

export const defaultProducts = [
  {
    name: "Barre chocolatée (Dairy Milk)",
    sku: "BIF-CHOC-DMILK-001",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "paquet",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Chewing-gum (paquet)",
    sku: "BIF-CHEWGUM-002",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "box",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Chips (Simba) 150g",
    sku: "BIF-CHIPS-SIMBA-150G-003",
    category: "Snacks & Confiserie",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "paquet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Chips (Pringles) 165g",
    sku: "BIF-CHIPS-PRING-165G-004",
    category: "Snacks & Confiserie",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "tube",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Wafers & Crackers (paquet)",
    sku: "BIF-WAFER-005",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "carton",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Popcorn (paquet)",
    sku: "BIF-POPCORN-006",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "box",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Bonbons / Confiserie (sachet)",
    sku: "BIF-CANDY-007",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "sachet",
    purchaseUnit: "box",
    sellingUnit: "sachet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Arachides grillées (sachet)",
    sku: "BIF-PEANUT-008",
    category: "Snacks & Confiserie",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "sachet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Maïs rôti (sachet)",
    sku: "BIF-ROASTMAIZE-009",
    category: "Snacks & Confiserie",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "sachet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Biscuits (paquet)",
    sku: "BIF-BISCUIT-010",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "carton",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Barres céréalières (paquet)",
    sku: "BIF-GRANOLA-011",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "box",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Gaufrettes (paquet)",
    sku: "BIF-WAFLE-012",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "carton",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Chocolat tablette (paquet)",
    sku: "BIF-CHOC-TABLET-013",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "paquet",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Beignets & Donuts (pièce)",
    sku: "BIF-DONUT-014",
    category: "Snacks & Confiserie",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "piece",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  // ---------------------- 12. FRESH FRUITS & VEGETABLES ----------------------
  {
    name: "Bananes vertes (matoke)",
    sku: "BIF-FRU-BANANE-MATOKE-1KG-001",
    category: "Fruits & Légumes Frais",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Bananes mûres",
    sku: "BIF-FRU-BANANE-MURE-1KG-001",
    category: "Fruits & Légumes Frais",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "régime",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Avocats frais",
    sku: "BIF-FRU-AVOCAT-1PC-001",
    category: "Fruits & Légumes Frais",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "sac",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Mangues fraîches",
    sku: "BIF-FRU-MANGUE-1PC-001",
    category: "Fruits & Légumes Frais",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "caisse",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Ananas frais",
    sku: "BIF-FRU-ANANAS-1PC-001",
    category: "Fruits & Légumes Frais",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "sac",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Oranges fraîches",
    sku: "BIF-FRU-ORANGE-1PC-001",
    category: "Fruits & Légumes Frais",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "caisse",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Citrons (citron vert)",
    sku: "BIF-FRU-CITRON-1PC-001",
    category: "Fruits & Légumes Frais",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "caisse",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Tomates fraîches",
    sku: "BIF-FRU-TOMATE-1KG-001",
    category: "Fruits & Légumes Frais",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "caisse",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Oignons rouges",
    sku: "BIF-FRU-OIGNON-ROUGE-1KG-001",
    category: "Fruits & Légumes Frais",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Chou (cabbage)",
    sku: "BIF-FRU-CHOU-1PC-001",
    category: "Fruits & Légumes Frais",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "sac",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Carottes",
    sku: "BIF-FRU-CAROTTE-1KG-001",
    category: "Fruits & Légumes Frais",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Légumes verts (lengalenga / dodo / épinard)",
    sku: "BIF-FRU-LEGUME-VERT-1KG-001",
    category: "Fruits & Légumes Frais",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },

  // ---------------------- 13. SEEDS, NUTS & LEGUMES ----------------------
  {
    name: "Arachides grillées",
    sku: "BIF-LEG-ARACHIDE-GRILL-1KG-001",
    category: "Graines, Noix & Légumineuses",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Arachides crues",
    sku: "BIF-LEG-ARACHIDE-CRUE-1KG-001",
    category: "Graines, Noix & Légumineuses",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Graines de tournesol",
    sku: "BIF-LEG-TOURNESOL-1KG-001",
    category: "Graines, Noix & Légumineuses",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Graines de chia",
    sku: "BIF-LEG-CHIA-1KG-001",
    category: "Graines, Noix & Légumineuses",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Graines de sésame",
    sku: "BIF-LEG-SESAME-1KG-001",
    category: "Graines, Noix & Légumineuses",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Pâte d'arachide (beurre de cacahuète)",
    sku: "BIF-LEG-PATE-ARACHIDE-500G-001",
    category: "Graines, Noix & Légumineuses",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "g",
    purchaseUnit: "pot",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },

  // ---------------------- 14. BABY & INFANT FOODS ----------------------
  {
    name: "Farine lactée (Cerelac)",
    sku: "BIF-BAB-CERELAC-400G-001",
    category: "Aliments Bébé",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "g",
    purchaseUnit: "boîte",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Lait infantile (Nan 1, Nan 2, etc.)",
    sku: "BIF-BAB-NAN-400G-001",
    category: "Aliments Bébé",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "g",
    purchaseUnit: "boîte",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Mélange de bouillie bébé",
    sku: "BIF-BAB-BOUILLIE-500G-001",
    category: "Aliments Bébé",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "g",
    purchaseUnit: "sachet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Biscuits pour bébé",
    sku: "BIF-BAB-BISCUIT-1PC-001",
    category: "Aliments Bébé",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "boîte",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },

  // ---------------------- 15. FROZEN FOODS ----------------------
  {
    name: "Poulet congelé (entier)",
    sku: "BIF-FRO-POULET-ENTIER-1KG-001",
    category: "Produits Surgelés",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "carton",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Légumes congelés (mélange)",
    sku: "BIF-FRO-LEGUME-MIX-1KG-001",
    category: "Produits Surgelés",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "kg",
    purchaseUnit: "sachet",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Frites surgelées (pommes frites)",
    sku: "BIF-FRO-FRITE-1KG-001",
    category: "Produits Surgelés",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "kg",
    purchaseUnit: "sachet",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Blocs de glace (pour vendeurs de jus)",
    sku: "BIF-FRO-GLACE-BLOC-1PC-001",
    category: "Produits Surgelés",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "sac",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0,
  },
  {
    name: "Œufs (plateau 30)",
    sku: "BIF-OEUF-STD-30PCS-001",
    category: "Œufs & Volaille",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "plateau",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Œufs bio (plateau 30)",
    sku: "BIF-OEUF-BIO-30PCS-002",
    category: "Œufs & Volaille",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "plateau",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Poulet vivant (par pièce)",
    sku: "BIF-POULET-LIVE-1PC-001",
    category: "Œufs & Volaille",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "piece",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Poulet prêt-à-cuire (surgelé)",
    sku: "BIF-POULET-FROZEN-1PC-002",
    category: "Œufs & Volaille",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "piece",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Eau minérale 1L",
    sku: "BIF-EAU-1L-001",
    category: "Boissons",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Eau minérale 1.5L",
    sku: "BIF-EAU-1_5L-002",
    category: "Boissons",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Eau minérale 5L",
    sku: "BIF-EAU-5L-003",
    category: "Boissons",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "jerrican",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Eau minérale 18L",
    sku: "BIF-EAU-18L-004",
    category: "Boissons",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bidon",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Eau minérale 20L",
    sku: "BIF-EAU-20L-005",
    category: "Boissons",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bidon",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Coca-Cola (multiple sizes)
  {
    name: "Coca-Cola 33cl (canette)",
    sku: "BIF-COCA-033CL-006",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "canette",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Coca-Cola 35cl",
    sku: "BIF-COCA-035CL-007",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Coca-Cola 50cl",
    sku: "BIF-COCA-050CL-008",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Coca-Cola 1L",
    sku: "BIF-COCA-1L-009",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Coca-Cola 1.5L",
    sku: "BIF-COCA-1_5L-010",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Fanta (same sizes)
  {
    name: "Fanta Orange 33cl (canette)",
    sku: "BIF-FANTA-033CL-011",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "canette",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Fanta Orange 50cl",
    sku: "BIF-FANTA-050CL-012",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Fanta Orange 1L",
    sku: "BIF-FANTA-1L-013",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Fanta Orange 1.5L",
    sku: "BIF-FANTA-1_5L-014",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Sprite
  {
    name: "Sprite 33cl (canette)",
    sku: "BIF-SPRITE-033CL-015",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "canette",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Sprite 50cl",
    sku: "BIF-SPRITE-050CL-016",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Sprite 1L",
    sku: "BIF-SPRITE-1L-017",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Sprite 1.5L",
    sku: "BIF-SPRITE-1_5L-018",
    category: "Boissons gazeuses",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Energy drinks
  {
    name: "Sting 33cl",
    sku: "BIF-STING-033CL-019",
    category: "Boissons énergétiques",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "canette",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Malta 33cl",
    sku: "BIF-MALTA-033CL-020",
    category: "Boissons énergétiques",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Red Bull 25cl",
    sku: "BIF-REDBULL-025CL-021",
    category: "Boissons énergétiques",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "canette",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Monster 50cl",
    sku: "BIF-MONSTER-050CL-022",
    category: "Boissons énergétiques",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "canette",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Juices (brands & sizes)
  {
    name: "Afia jus 1L",
    sku: "BIF-AFIA-1L-023",
    category: "Jus",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "brique",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Afia jus 500ml",
    sku: "BIF-AFIA-500ML-024",
    category: "Jus",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Ceres jus 1L",
    sku: "BIF-CERES-1L-025",
    category: "Jus",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "brique",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "U-Fresh jus 500ml",
    sku: "BIF-UFRESH-500ML-026",
    category: "Jus",
    unitType: "volume",
    isWeighted: false,
    baseUnit: "ml",
    purchaseUnit: "bouteille",
    sellingUnit: "ml",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Tea
  {
    name: "Thé noir (paquet 100g)",
    sku: "BIF-THENOIR-100G-027",
    category: "Thé & Café",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "paquet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Thé vert (paquet 100g)",
    sku: "BIF-THEVERT-100G-028",
    category: "Thé & Café",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "paquet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Thé masala (paquet 100g)",
    sku: "BIF-THEMAS-100G-029",
    category: "Thé & Café",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "paquet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Coffee
  {
    name: "Café Africafé 200g",
    sku: "BIF-AFRICAFE-200G-030",
    category: "Thé & Café",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "paquet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Café en grains 500g",
    sku: "BIF-COFFEEBEAN-500G-031",
    category: "Thé & Café",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "sac",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },

  // Powder drink mixes
  {
    name: "Tang Orange 500g (poudre)",
    sku: "BIF-TANG-500G-032",
    category: "Boissons en poudre",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "paquet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Tang Tropical 500g (poudre)",
    sku: "BIF-TANG-TRP-500G-033",
    category: "Boissons en poudre",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "g",
    purchaseUnit: "paquet",
    sellingUnit: "g",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    stockQuantity: 0
  },
  {
    name: "Viande de bœuf",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-001",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Viande de chèvre",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-002",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Poulet entier",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-003",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Plateau d'œufs (30 œufs)",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-004",
    purchaseUnit: "plateau",
    sellingUnit: "plateau",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Poisson frais (Ndagala)",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-005",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Poisson frais (Capitaine)",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-006",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Poisson congelé (Maquereau)",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-007",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Poisson congelé (Tilapia)",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-008",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Saucisses / Hot-dogs",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-009",
    purchaseUnit: "kg",
    sellingUnit: "pièce",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Viande de porc",
    category: "Viandes, Poissons & Protéines",
    sku: "BIF-MEAT-010",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },  {
    name: "Haricots en conserve",
    category: "Conserves & Produits Emballés",
    sku: "BIF-CANBEAN-001",
    baseUnit: "boîte",
    purchaseUnit: "carton",
    sellingUnit: "boîte",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Pâte de tomate",
    category: "Conserves & Produits Emballés",
    sku: "BIF-TOMPSTE-002",
    baseUnit: "sachet",
    purchaseUnit: "carton",
    sellingUnit: "sachet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sardines en boîte",
    category: "Conserves & Produits Emballés",
    sku: "BIF-SARDINE-003",
    baseUnit: "boîte",
    purchaseUnit: "carton",
    sellingUnit: "boîte",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Thon en conserve",
    category: "Conserves & Produits Emballés",
    sku: "BIF-THONCAN-004",
    baseUnit: "boîte",
    purchaseUnit: "carton",
    sellingUnit: "boîte",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Maquereau en boîte",
    category: "Conserves & Produits Emballés",
    sku: "BIF-MACKCAN-005",
    baseUnit: "boîte",
    purchaseUnit: "carton",
    sellingUnit: "boîte",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Légumes en conserve",
    category: "Conserves & Produits Emballés",
    sku: "BIF-CANVEG-006",
    baseUnit: "boîte",
    purchaseUnit: "carton",
    sellingUnit: "boîte",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Fruits en conserve",
    category: "Conserves & Produits Emballés",
    sku: "BIF-CANFRUIT-007",
    baseUnit: "boîte",
    purchaseUnit: "carton",
    sellingUnit: "boîte",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sauces prêtes à l'emploi",
    category: "Conserves & Produits Emballés",
    sku: "BIF-READYSC-008",
    baseUnit: "bouteille",
    purchaseUnit: "carton",
    sellingUnit: "bouteille",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Nouilles instantanées (Indomie)",
    category: "Conserves & Produits Emballés",
    sku: "BIF-INDOMIE-009",
    baseUnit: "paquet",
    purchaseUnit: "carton",
    sellingUnit: "paquet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Lait frais",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-001",
    purchaseUnit: "litre",
    sellingUnit: "litre",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Lait en poudre (Nido)",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-002",
    purchaseUnit: "kg",
    sellingUnit: "gramme",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Lait en poudre (Cowbell)",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-003",
    purchaseUnit: "kg",
    sellingUnit: "gramme",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Yaourt",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-004",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Fromage",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-005",
    purchaseUnit: "kg",
    sellingUnit: "gramme",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Beurre",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-006",
    purchaseUnit: "kg",
    sellingUnit: "gramme",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Ghee",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-007",
    purchaseUnit: "kg",
    sellingUnit: "gramme",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Glace (Ice cream)",
    category: "Produits Laitiers",
    sku: "BIF-DAIRY-008",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitPrice: 0,
    sellingUnitPrice: 0,
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    stock: 0
  },
  {
    name: "Huile de tournesol",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-HUITOUR-001",
    baseUnit: "l",
    purchaseUnit: "carton",
    sellingUnit: "l",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Huile de palme rouge",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-HUIPALM-002",
    baseUnit: "l",
    purchaseUnit: "bidon",
    sellingUnit: "l",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Huile de soja",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-HUISOJA-003",
    baseUnit: "l",
    purchaseUnit: "carton",
    sellingUnit: "l",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Huile d'olive",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-HUIOLIV-004",
    baseUnit: "l",
    purchaseUnit: "carton",
    sellingUnit: "l",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Margarine",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-MARGA-005",
    baseUnit: "kg",
    purchaseUnit: "carton",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Beurre",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-BEURRE-006",
    baseUnit: "kg",
    purchaseUnit: "carton",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sel",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-SEL-007",
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Épices en boîte (Royco, Maggi, PilPil)",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-EPIBOX-008",
    baseUnit: "boîte",
    purchaseUnit: "carton",
    sellingUnit: "boîte",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Poivre",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-POIVRE-009",
    baseUnit: "sachet",
    purchaseUnit: "carton",
    sellingUnit: "sachet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Curry",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-CURRY-010",
    baseUnit: "sachet",
    purchaseUnit: "carton",
    sellingUnit: "sachet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Cannelle",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-CANNEL-011",
    baseUnit: "sachet",
    purchaseUnit: "carton",
    sellingUnit: "sachet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Ail en poudre",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-AILPD-012",
    baseUnit: "sachet",
    purchaseUnit: "carton",
    sellingUnit: "sachet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Mayonnaise",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-MAYO-013",
    baseUnit: "bocal",
    purchaseUnit: "carton",
    sellingUnit: "bocal",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Ketchup",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-KETCH-014",
    baseUnit: "bouteille",
    purchaseUnit: "carton",
    sellingUnit: "bouteille",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Moutarde",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-MOUTAR-015",
    baseUnit: "bocal",
    purchaseUnit: "carton",
    sellingUnit: "bocal",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sauce soja",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-SAUCSOJ-016",
    baseUnit: "bouteille",
    purchaseUnit: "carton",
    sellingUnit: "bouteille",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sauce piment",
    category: "Huiles, Condiments & Épices",
    sku: "BIF-SAUCPIM-017",
    baseUnit: "bouteille",
    purchaseUnit: "carton",
    sellingUnit: "bouteille",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sucre blanc",
    category: "Sucre & Édulcorants",
    sku: "BIF-SUCBL-001",
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sucre brun",
    category: "Sucre & Édulcorants",
    sku: "BIF-SUCBR-002",
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Miel",
    category: "Sucre & Édulcorants",
    sku: "BIF-MIEL-003",
    baseUnit: "pot",
    purchaseUnit: "carton",
    sellingUnit: "pot",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Confiture",
    category: "Sucre & Édulcorants",
    sku: "BIF-CONFIT-004",
    baseUnit: "pot",
    purchaseUnit: "carton",
    sellingUnit: "pot",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sirop",
    category: "Sucre & Édulcorants",
    sku: "BIF-SIROP-005",
    baseUnit: "bouteille",
    purchaseUnit: "carton",
    sellingUnit: "bouteille",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Sucre glace",
    category: "Sucre & Édulcorants",
    sku: "BIF-SUCGC-006",
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Cassonade",
    category: "Sucre & Édulcorants",
    sku: "BIF-CASSON-007",
    baseUnit: "kg",
    purchaseUnit: "sac",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Haricots rouges",
    sku: "BIF-BEANS-010",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Haricots jaunes",
    sku: "BIF-BEANS-011",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Haricots blancs (kidney)",
    sku: "BIF-BEANS-012",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Lentilles",
    sku: "BIF-LENT-013",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Pois secs",
    sku: "BIF-PEAS-014",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Soja",
    sku: "BIF-SOYA-015",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Farine de manioc (Ubugali)",
    sku: "BIF-MANIO-016",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },

  {
    name: "Pommes de terre (Irish)",
    sku: "BIF-PDT-017",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: true,
    defaultExpiryDays: 7,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Patates douces",
    sku: "BIF-SWEET-018",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: true,
    defaultExpiryDays: 7,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Bananes plantains (vertes)",
    sku: "BIF-PLANT-019",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "piece",
    isWeighted: false,
    baseUnit: "piece",
    purchaseUnit: "piece",
    sellingUnit: "piece",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 20,
    isActive: true,
    isPerishable: true,
    defaultExpiryDays: 5,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Pâtes alimentaires (spaghetti)",
    sku: "BIF-SPAG-020",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Pâtes alimentaires (macaroni)",
    sku: "BIF-MACAR-021",
    category: "Aliments de base / Produits secs",
    description: "",
    unitType: "weight",
    isWeighted: false,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Riz blanc",
    sku: "BIF-RICE-001",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Farine de maïs (Ikigori)",
    sku: "BIF-MAIZ-002",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Farine de blé",
    sku: "BIF-WHEAT-003",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Sorgho",
    sku: "BIF-SORGH-004",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Millet",
    sku: "BIF-MILL-005",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Avoine (flocons d’avoine)",
    sku: "BIF-OATS-006",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Semoule",
    sku: "BIF-SEMOU-007",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Couscous",
    sku: "BIF-COUSC-008",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Farine pour bouillie (Porridge)",
    sku: "BIF-BOUIL-009",
    category: "Céréales & Grains",
    description: "",
    unitType: "weight",
    isWeighted: true,
    baseUnit: "kg",
    purchaseUnit: "kg",
    sellingUnit: "kg",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPricePerBase: 0,
    sellingPricePerBase: 0,
    wholesalePricePerBase: 0,
    lowStockThreshold: 10,
    isActive: true,
    isPerishable: false,
    defaultExpiryDays: 0,
    imageUrl: "",
    imageThumbnailUrl: "",
  },
  {
    name: "Pain baguette",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-PAINBG-001",
    baseUnit: "pièce",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Pain carré",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-PAINCR-002",
    baseUnit: "pièce",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Gâteau",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-GATEAU-003",
    baseUnit: "pièce",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Biscuits",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-BISCUIT-004",
    baseUnit: "paquet",
    purchaseUnit: "carton",
    sellingUnit: "paquet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Beignets",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-BEIGNET-005",
    baseUnit: "pièce",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Mandazi",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-MANDAZI-006",
    baseUnit: "pièce",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Chapati",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-CHAPATI-007",
    baseUnit: "pièce",
    purchaseUnit: "pièce",
    sellingUnit: "pièce",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  },
  {
    name: "Cookies",
    category: "Boulangerie & Pâtisserie",
    sku: "BIF-COOKIE-008",
    baseUnit: "paquet",
    purchaseUnit: "carton",
    sellingUnit: "paquet",
    purchaseUnitSize: 0,
    unitConversionFactor: 0,
    costPrice: 0,
    wholesalePrice: 0,
    sellingPrice: 0,
    barcode: null
  }
]

