// -------------------------
// COMPREHENSIVE BURUNDI PRODUCT TEMPLATES
// -------------------------
const BURUNDI_TEMPLATES = [
  {
    id: "groceries",
    name: "Épicerie & Alimentation",
    icon: "storefront-outline",
    color: "#10B981",
    description: "Produits alimentaires de base et épicerie",
    products: [
      { name: "Sucre blanc", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 50 },
      { name: "Riz local", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 50 },
      { name: "Farine de blé", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Farine de maïs", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Huile végétale", category: "food", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 20 },
      { name: "Huile de palme", category: "food", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 5 },
      { name: "Sel iodé", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "sachet", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Haricots rouges", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 50 },
      { name: "Haricots blancs", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 50 },
      { name: "Pois cassés", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Lentilles", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Pâtes alimentaires", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Spaghetti", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Thé en sachets", category: "food", unitType: "pack", baseUnit: "sachet", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Café instantané", category: "food", unitType: "weight", baseUnit: "g", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Cacao en poudre", category: "food", unitType: "weight", baseUnit: "g", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Lait en poudre", category: "food", unitType: "weight", baseUnit: "g", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 400 },
      { name: "Bouillon cube", category: "food", unitType: "piece", baseUnit: "cube", sellingUnit: "cube", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Tomate concentrée", category: "food", unitType: "weight", baseUnit: "g", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 48 },
      { name: "Sardines en boîte", category: "food", unitType: "piece", baseUnit: "boite", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 48 },
      { name: "Corned beef", category: "food", unitType: "weight", baseUnit: "g", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Mayonnaise", category: "food", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Ketchup", category: "food", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Biscuits", category: "food", unitType: "pack", baseUnit: "pack", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Bonbons", category: "food", unitType: "weight", baseUnit: "g", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Chocolat", category: "food", unitType: "piece", baseUnit: "barre", sellingUnit: "barre", purchaseUnit: "carton", purchaseUnitSize: 24 },
    ]
  },
  {
    id: "drinks",
    name: "Boissons & Liquides",
    icon: "wine-outline",
    color: "#3B82F6",
    description: "Boissons non-alcoolisées et alcoolisées",
    products: [
      { name: "Eau minérale 1.5L", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Eau minérale 0.5L", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Soda Coca-Cola 33cl", category: "drinks", unitType: "piece", baseUnit: "can", sellingUnit: "can", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Soda Fanta 33cl", category: "drinks", unitType: "piece", baseUnit: "can", sellingUnit: "can", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Soda Sprite 33cl", category: "drinks", unitType: "piece", baseUnit: "can", sellingUnit: "can", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Bière Primus 65cl", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Bière Primus 33cl", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Bière Amstel 50cl", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Vin rouge", category: "drinks", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Vin blanc", category: "drinks", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Whisky", category: "drinks", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Vodka", category: "drinks", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Jus de fruits 1L", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Jus de fruits 0.5L", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Lait frais 1L", category: "drinks", unitType: "piece", baseUnit: "sachet", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Yaourt nature", category: "drinks", unitType: "piece", baseUnit: "pot", sellingUnit: "pot", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Yaourt aux fruits", category: "drinks", unitType: "piece", baseUnit: "pot", sellingUnit: "pot", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Boisson énergisante", category: "drinks", unitType: "piece", baseUnit: "can", sellingUnit: "can", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Eau gazeuse", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Sirop de grenadine", category: "drinks", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Café prêt à boire", category: "drinks", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 24 },
    ]
  },
  {
    id: "clothing",
    name: "Vêtements & Textiles",
    icon: "shirt-outline",
    color: "#8B5CF6",
    description: "Vêtements, chaussures et accessoires",
    products: [
      { name: "T-shirt homme", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "T-shirt femme", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Chemise homme", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Chemise femme", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Pantalon jean homme", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Pantalon jean femme", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Pantalon costume", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Robe simple", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Robe de soirée", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Jupe", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Short", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 40 },
      { name: "Pull-over", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Veste légère", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Manteau", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Chaussures homme", category: "clothing", unitType: "piece", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Chaussures femme", category: "clothing", unitType: "piece", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Sandales", category: "clothing", unitType: "piece", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Tongues", category: "clothing", unitType: "piece", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Chaussettes", category: "clothing", unitType: "pack", baseUnit: "pair", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Sous-vêtements homme", category: "clothing", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Sous-vêtements femme", category: "clothing", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Cravate", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Ceinture", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 40 },
      { name: "Chapeau/casquette", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Écharpe", category: "clothing", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 40 },
    ]
  },
  {
    id: "pharmacy",
    name: "Pharmacie & Santé",
    icon: "medical-outline",
    color: "#EF4444",
    description: "Médicaments et produits de santé",
    products: [
      { name: "Paracétamol 500mg", category: "health", unitType: "pack", baseUnit: "comprimé", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Ibuprofène 400mg", category: "health", unitType: "pack", baseUnit: "comprimé", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Aspirine", category: "health", unitType: "pack", baseUnit: "comprimé", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Antibiotique (Amoxicilline)", category: "health", unitType: "pack", baseUnit: "comprimé", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Antipaludéen", category: "health", unitType: "pack", baseUnit: "comprimé", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Antidiarrhéique", category: "health", unitType: "pack", baseUnit: "sachet", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Vitamine C", category: "health", unitType: "pack", baseUnit: "comprimé", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Multivitamines", category: "health", unitType: "pack", baseUnit: "comprimé", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Pansements adhésifs", category: "health", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Seringues stériles", category: "health", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Compresses stériles", category: "health", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Désinfectant (Bétadine)", category: "health", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Alcool à 70°", category: "health", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Thermomètre digital", category: "health", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Tensiomètre", category: "health", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Préservatifs", category: "health", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Test de grossesse", category: "health", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Savon antiseptique", category: "personal-care", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 48 },
      { name: "Savon de toilette", category: "personal-care", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 72 },
      { name: "Shampoing", category: "personal-care", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Après-shampoing", category: "personal-care", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Dentifrice", category: "personal-care", unitType: "piece", baseUnit: "tube", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Brosse à dents", category: "personal-care", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Déodorant", category: "personal-care", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Crème hydratante", category: "personal-care", unitType: "volume", baseUnit: "ml", sellingUnit: "pot", purchaseUnit: "carton", purchaseUnitSize: 24 },
    ]
  },
  {
    id: "electronics",
    name: "Électronique & Téléphonie",
    icon: "hardware-chip-outline",
    color: "#F59E0B",
    description: "Appareils électroniques et accessoires",
    products: [
      { name: "Smartphone", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Téléphone basique", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Chargeur téléphone", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Câble USB", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Power bank", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Écouteurs filaires", category: "electronics", unitType: "piece", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Écouteurs Bluetooth", category: "electronics", unitType: "piece", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Haut-parleur portable", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Radio FM", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Télévision LED 32\"", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 4 },
      { name: "Décodeur TV", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Antenne TV", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Ventilateur électrique", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 8 },
      { name: "Fer à repasser", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Bouilloire électrique", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Plaque chauffante", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Lampe torche", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Piles AA", category: "electronics", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Piles AAA", category: "electronics", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Adaptateur secteur", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Carte mémoire SD", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Clé USB 16GB", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Casque VR", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Montre connectée", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Tablette tactile", category: "electronics", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
    ]
  },
  {
    id: "construction",
    name: "Matériaux Construction",
    icon: "hammer-outline",
    color: "#6366F1",
    description: "Matériaux de construction et quincaillerie",
    products: [
      { name: "Ciment 50kg", category: "construction", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "palette", purchaseUnitSize: 1000 },
      { name: "Ciment 25kg", category: "construction", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "palette", purchaseUnitSize: 2000 },
      { name: "Sable", category: "construction", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "camion", purchaseUnitSize: 10000 },
      { name: "Gravier", category: "construction", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "camion", purchaseUnitSize: 10000 },
      { name: "Briques", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "palette", purchaseUnitSize: 500 },
      { name: "Parpaings", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "palette", purchaseUnitSize: 200 },
      { name: "Tôles ondulées", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "lot", purchaseUnitSize: 50 },
      { name: "Peinture blanche", category: "construction", unitType: "volume", baseUnit: "l", sellingUnit: "bidon", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Peinture couleur", category: "construction", unitType: "volume", baseUnit: "l", sellingUnit: "bidon", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Vernis", category: "construction", unitType: "volume", baseUnit: "l", sellingUnit: "bidon", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Solvant", category: "construction", unitType: "volume", baseUnit: "l", sellingUnit: "bidon", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Clous divers", category: "construction", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Vis", category: "construction", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Écrous et boulons", category: "construction", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Ciment colle", category: "construction", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "palette", purchaseUnitSize: 500 },
      { name: "Enduit de lissage", category: "construction", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "palette", purchaseUnitSize: 500 },
      { name: "Carreaux de céramique", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "m²", purchaseUnit: "palette", purchaseUnitSize: 100 },
      { name: "Planches de bois", category: "construction", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "lot", purchaseUnitSize: 100 },
      { name: "Poutres", category: "construction", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "lot", purchaseUnitSize: 50 },
      { name: "Porte en bois", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "lot", purchaseUnitSize: 10 },
      { name: "Fenêtre PVC", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "lot", purchaseUnitSize: 10 },
      { name: "Gouttières", category: "construction", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "lot", purchaseUnitSize: 50 },
      { name: "Tuyaux PVC", category: "construction", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "lot", purchaseUnitSize: 100 },
      { name: "Robinets", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Ampoules LED", category: "construction", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
    ]
  },
  {
    id: "agriculture",
    name: "Agriculture",
    icon: "leaf-outline",
    color: "#22C55E",
    description: "Produits agricoles et intrants",
    products: [
      { name: "Engrais NPK", category: "agriculture", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "palette", purchaseUnitSize: 1000 },
      { name: "Urée", category: "agriculture", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "palette", purchaseUnitSize: 1000 },
      { name: "Semences de maïs", category: "agriculture", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 50 },
      { name: "Semences de riz", category: "agriculture", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Semences de haricots", category: "agriculture", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Pesticide", category: "agriculture", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 20 },
      { name: "Herbicide", category: "agriculture", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 10 },
      { name: "Fongicide", category: "agriculture", unitType: "weight", baseUnit: "g", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Pulvérisateur", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Machette", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Houe", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Râteau", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Pelle", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Arrosoir", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Seau plastique", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Filet de protection", category: "agriculture", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "rouleau", purchaseUnitSize: 100 },
      { name: "Bâche plastique", category: "agriculture", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "rouleau", purchaseUnitSize: 50 },
      { name: "Gants de jardinage", category: "agriculture", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Bottes en caoutchouc", category: "agriculture", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Serre tunnel", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 4 },
      { name: "Tuteur bambou", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "fagot", purchaseUnitSize: 100 },
      { name: "Corde agricole", category: "agriculture", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "rouleau", purchaseUnitSize: 100 },
      { name: "Balance agricole", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Sécateur", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Greffoir", category: "agriculture", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
    ]
  },
  {
    id: "beauty",
    name: "Beauté & Cosmétiques",
    icon: "sparkles-outline",
    color: "#EC4899",
    description: "Produits de beauté et cosmétiques",
    products: [
      { name: "Fond de teint", category: "beauty", unitType: "piece", baseUnit: "boite", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Poudre compacte", category: "beauty", unitType: "piece", baseUnit: "boite", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Rouge à lèvres", category: "beauty", unitType: "piece", baseUnit: "tube", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 36 },
      { name: "Mascara", category: "beauty", unitType: "piece", baseUnit: "tube", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Eye-liner", category: "beauty", unitType: "piece", baseUnit: "stylo", sellingUnit: "stylo", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Fard à paupières", category: "beauty", unitType: "piece", baseUnit: "palette", sellingUnit: "palette", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Vernis à ongles", category: "beauty", unitType: "piece", baseUnit: "bouteille", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 48 },
      { name: "Démaquillant", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Crème de jour", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "pot", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Crème de nuit", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "pot", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Crème solaire", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Lotion tonique", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Masque facial", category: "beauty", unitType: "piece", baseUnit: "sachet", sellingUnit: "sachet", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Gommage visage", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Parfum femme", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Parfum homme", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Eau de Cologne", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Lotion après-rasage", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Mousse à raser", category: "beauty", unitType: "volume", baseUnit: "ml", sellingUnit: "bombe", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Rasoir jetable", category: "beauty", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Lames de rasoir", category: "beauty", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Coton démaquillant", category: "beauty", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Lingettes démaquillantes", category: "beauty", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Peigne", category: "beauty", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Brosse à cheveux", category: "beauty", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 36 },
    ]
  },
  {
    id: "household",
    name: "Articles Ménagers",
    icon: "home-outline",
    color: "#06B6D4",
    description: "Produits ménagers et entretien",
    products: [
      { name: "Lessive en poudre", category: "household", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Lessive liquide", category: "household", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Adoucissant", category: "household", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Détergent vaisselle", category: "household", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Éponge vaisselle", category: "household", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Liquide vaiselle", category: "household", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Javel", category: "household", unitType: "volume", baseUnit: "l", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Désodorisant air", category: "household", unitType: "piece", baseUnit: "bombe", sellingUnit: "bombe", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Insecticide", category: "household", unitType: "piece", baseUnit: "bombe", sellingUnit: "bombe", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Nettoyant multi-surfaces", category: "household", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Nettoyant vitres", category: "household", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Cire meubles", category: "household", unitType: "volume", baseUnit: "ml", sellingUnit: "pot", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Balai", category: "household", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Brosse WC", category: "household", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Seau plastique", category: "household", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Serpillère", category: "household", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Gants ménagers", category: "household", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Sac poubelle", category: "household", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Papier aluminium", category: "household", unitType: "length", baseUnit: "m", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Film étirable", category: "household", unitType: "length", baseUnit: "m", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Papier sulfurisé", category: "household", unitType: "length", baseUnit: "m", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Allumettes", category: "household", unitType: "pack", baseUnit: "boite", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Briquet", category: "household", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Bougie", category: "household", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Ruban adhésif", category: "household", unitType: "piece", baseUnit: "rouleau", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 50 },
    ]
  },
  {
    id: "stationery",
    name: "Papeterie & Bureau",
    icon: "pencil-outline",
    color: "#8B5CF6",
    description: "Fournitures de bureau et scolaire",
    products: [
      { name: "Cahier 96 pages", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Cahier 200 pages", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Stylo bic bleu", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Stylo bic rouge", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Stylo bic noir", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Crayon à papier", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Gomme", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Taille-crayon", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Règle 30cm", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Équerre", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Rapporteur", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Compas", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Feutre coloré", category: "stationery", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Crayon de couleur", category: "stationery", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Peinture gouache", category: "stationery", unitType: "piece", baseUnit: "pot", sellingUnit: "pot", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Pinceau", category: "stationery", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Colle en bâton", category: "stationery", unitType: "piece", baseUnit: "bâton", sellingUnit: "bâton", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Colle liquide", category: "stationery", unitType: "volume", baseUnit: "ml", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Scotch", category: "stationery", unitType: "piece", baseUnit: "rouleau", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Trombones", category: "stationery", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Agrafeuse", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Agrafes", category: "stationery", unitType: "pack", baseUnit: "boite", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Calculatrice", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Papier A4", category: "stationery", unitType: "pack", baseUnit: "rame", sellingUnit: "rame", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Classeur", category: "stationery", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
    ]
  },
  {
    id: "automotive",
    name: "Automobile & Pièces",
    icon: "car-outline",
    color: "#64748B",
    description: "Pièces auto et accessoires véhicules",
    products: [
      { name: "Pneu 165/70R13", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "lot", purchaseUnitSize: 10 },
      { name: "Pneu 185/65R14", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "lot", purchaseUnitSize: 8 },
      { name: "Huile moteur 15W40", category: "automotive", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Huile moteur 20W50", category: "automotive", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Filtre à air", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Filtre à huile", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Filtre à carburant", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Batterie 45Ah", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "palette", purchaseUnitSize: 12 },
      { name: "Batterie 60Ah", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "palette", purchaseUnitSize: 10 },
      { name: "Ampoule phare H4", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Ampoule clignotant", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Liquide de frein", category: "automotive", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Liquide refroidissement", category: "automotive", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Liquide lave-glace", category: "automotive", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Bougies d'allumage", category: "automotive", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Courroie distribution", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Courroie alternateur", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Plaquettes de frein", category: "automotive", unitType: "pack", baseUnit: "jeu", sellingUnit: "jeu", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Disques de frein", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Essuie-glace", category: "automotive", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Antigel", category: "automotive", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Gazole", category: "automotive", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 200 },
      { name: "Essence", category: "automotive", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 200 },
      { name: "Cric", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Clé à molette", category: "automotive", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
    ]
  },
  {
    id: "sports",
    name: "Sports & Loisirs",
    icon: "american-football-outline",
    color: "#DC2626",
    description: "Articles de sport et loisirs",
    products: [
      { name: "Ballon de football", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Ballon de basket", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Ballon de volley", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Maillot de football", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Short de sport", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 40 },
      { name: "Chaussures de sport", category: "sports", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Raquette de tennis", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Balles de tennis", category: "sports", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Raquette de badminton", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Volant de badminton", category: "sports", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Corde à sauter", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Haltères 5kg", category: "sports", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Haltères 10kg", category: "sports", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Tapis de yoga", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Vélo d'exercice", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 3 },
      { name: "Tapis de course", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 2 },
      { name: "Sac de sport", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Gourde sportive", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Bandeau de sudation", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Protège-tibias", category: "sports", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Gants de boxe", category: "sports", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Casque vélo", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Bâtons de marche", category: "sports", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Tente 2 places", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Sac de couchage", category: "sports", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
    ]
  },
  {
    id: "baby",
    name: "Bébé & Puériculture",
    icon: "baby-outline",
    color: "#F472B6",
    description: "Produits pour bébés et jeunes enfants",
    products: [
      { name: "Couches taille 1", category: "baby", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Couches taille 2", category: "baby", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Couches taille 3", category: "baby", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Couches taille 4", category: "baby", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Lait infantile 1er âge", category: "baby", unitType: "weight", baseUnit: "g", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Lait infantile 2ème âge", category: "baby", unitType: "weight", baseUnit: "g", sellingUnit: "boite", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Biberon 250ml", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Tétine biberon", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Sucette", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Bavoir", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Body bébé 0-3 mois", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Body bébé 3-6 mois", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 40 },
      { name: "Pyjama bébé", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Chaussons bébé", category: "baby", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 40 },
      { name: "Bonnet bébé", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Lingettes bébé", category: "baby", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Crème pour bébé", category: "baby", unitType: "volume", baseUnit: "ml", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Lait de toilette", category: "baby", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Shampoing bébé", category: "baby", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Baignoire bébé", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Thermomètre bain", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Tapis à langer", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Table à langer", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 4 },
      { name: "Poussette", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 2 },
      { name: "Siège auto bébé", category: "baby", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 4 },
    ]
  },
  {
    id: "restaurant",
    name: "Restaurant & Hôtellerie",
    icon: "restaurant-outline",
    color: "#F97316",
    description: "Produits pour restaurants et hôtels",
    products: [
      { name: "Riz basmati 5kg", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "sac", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Poulet entier", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "cageot", purchaseUnitSize: 50 },
      { name: "Bœuf haché", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Poisson frais", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "cageot", purchaseUnitSize: 30 },
      { name: "Oignons", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Tomates", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "cageot", purchaseUnitSize: 20 },
      { name: "Pommes de terre", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 50 },
      { name: "Carottes", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "sac", purchaseUnitSize: 25 },
      { name: "Choux", category: "food", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "cageot", purchaseUnitSize: 30 },
      { name: "Bananes plantain", category: "food", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "cageot", purchaseUnitSize: 30 },
      { name: "Assiettes jetables", category: "restaurant", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Gobelets jetables", category: "restaurant", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Couverts jetables", category: "restaurant", unitType: "pack", baseUnit: "set", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Serviettes de table", category: "restaurant", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Nappes jetables", category: "restaurant", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Torchons de cuisine", category: "restaurant", unitType: "pack", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Tabliers", category: "restaurant", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Bonnet de cuisine", category: "restaurant", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Gants cuisine", category: "restaurant", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Film alimentaire", category: "restaurant", unitType: "length", baseUnit: "m", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Papier sulfurisé", category: "restaurant", unitType: "length", baseUnit: "m", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Sacs congélation", category: "restaurant", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Contenants repas", category: "restaurant", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Bouteilles d'eau 33cl", category: "restaurant", unitType: "piece", baseUnit: "bottle", sellingUnit: "bottle", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Sachets de thé", category: "restaurant", unitType: "pack", baseUnit: "sachet", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
    ]
  },
  {
    id: "cleaning",
    name: "Nettoyage Professionnel",
    icon: "sparkles-outline",
    color: "#06B6D4",
    description: "Produits de nettoyage professionnel",
    products: [
      { name: "Détergent sols", category: "cleaning", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 20 },
      { name: "Nettoyant vitres", category: "cleaning", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 10 },
      { name: "Désinfectant surfaces", category: "cleaning", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 5 },
      { name: "Détergent WC", category: "cleaning", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 5 },
      { name: "Déboucheur canalisations", category: "cleaning", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 5 },
      { name: "Cire sols", category: "cleaning", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 5 },
      { name: "Dégraissant cuisine", category: "cleaning", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 10 },
      { name: "Balai professionnel", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Raclette vitres", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Seau avec essoreur", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 10 },
      { name: "Serpillère microfibre", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Chiffons microfibre", category: "cleaning", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Gants de protection", category: "cleaning", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Masque de protection", category: "cleaning", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Lunettes de protection", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Sac poubelle 100L", category: "cleaning", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Sac poubelle 50L", category: "cleaning", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 200 },
      { name: "Pelle et balayette", category: "cleaning", unitType: "set", baseUnit: "set", sellingUnit: "set", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Aspirateur industriel", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 4 },
      { name: "Nettoyeur vapeur", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 3 },
      { name: "Monobrosse", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 2 },
      { name: "Chariot de nettoyage", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 2 },
      { name: "Seau roulant", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Râteau à feuilles", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Brouette", category: "cleaning", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 3 },
    ]
  },
  {
    id: "hardware",
    name: "Quincaillerie",
    icon: "construct-outline",
    color: "#78716C",
    description: "Outils et fournitures de quincaillerie",
    products: [
      { name: "Marteau", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Tournevis plat", category: "hardware", unitType: "set", baseUnit: "piece", sellingUnit: "set", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Tournevis cruciforme", category: "hardware", unitType: "set", baseUnit: "piece", sellingUnit: "set", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Pince multiprise", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Pince coupante", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Clé à molette", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Clé Allen", category: "hardware", unitType: "set", baseUnit: "piece", sellingUnit: "set", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Scie à métaux", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Scie à bois", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 15 },
      { name: "Niveau à bulle", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Mètre ruban 5m", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Mètre ruban 8m", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Perceuse électrique", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 6 },
      { name: "Mèches à bois", category: "hardware", unitType: "set", baseUnit: "piece", sellingUnit: "set", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Mèches à béton", category: "hardware", unitType: "set", baseUnit: "piece", sellingUnit: "set", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Vis à bois", category: "hardware", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Vis à métal", category: "hardware", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Clous divers", category: "hardware", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Écrous et boulons", category: "hardware", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 500 },
      { name: "Rondelles", category: "hardware", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 1000 },
      { name: "Colle forte", category: "hardware", unitType: "volume", baseUnit: "ml", sellingUnit: "tube", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Ruban adhésif", category: "hardware", unitType: "piece", baseUnit: "rouleau", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Ruban isolant", category: "hardware", unitType: "piece", baseUnit: "rouleau", sellingUnit: "rouleau", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Câble électrique", category: "hardware", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "rouleau", purchaseUnitSize: 100 },
      { name: "Interrupteur", category: "hardware", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
    ]
  },
  {
    id: "petroleum",
    name: "Station Service",
    icon: "flash-outline",
    color: "#F59E0B",
    description: "Produits pétroliers et lubrifiants",
    products: [
      { name: "Essence super", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "citerne", purchaseUnitSize: 10000 },
      { name: "Gazole", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "citerne", purchaseUnitSize: 10000 },
      { name: "Kérosène", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 200 },
      { name: "Huile moteur 15W40", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Huile moteur 20W50", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Huile moteur 10W30", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 20 },
      { name: "Huile transmission", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Graisse lubrifiante", category: "petroleum", unitType: "weight", baseUnit: "kg", sellingUnit: "kg", purchaseUnit: "carton", purchaseUnitSize: 25 },
      { name: "Liquide de frein", category: "petroleum", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Liquide direction", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Antigel", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Additif carburant", category: "petroleum", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Nettoyant injecteurs", category: "petroleum", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Démarreur froid", category: "petroleum", unitType: "volume", baseUnit: "ml", sellingUnit: "bouteille", purchaseUnit: "carton", purchaseUnitSize: 24 },
      { name: "Pétrole lampant", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 20 },
      { name: "Huile végétale", category: "petroleum", unitType: "volume", baseUnit: "l", sellingUnit: "l", purchaseUnit: "bidon", purchaseUnitSize: 20 },
      { name: "Bidons 20L vides", category: "petroleum", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "palette", purchaseUnitSize: 50 },
      { name: "Bidons 5L vides", category: "petroleum", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Entonnoir", category: "petroleum", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 50 },
      { name: "Pompe manuelle", category: "petroleum", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 12 },
      { name: "Filtre à carburant", category: "petroleum", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
      { name: "Joint d'étanchéité", category: "petroleum", unitType: "pack", baseUnit: "piece", sellingUnit: "pack", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Tuyau d'essence", category: "petroleum", unitType: "length", baseUnit: "m", sellingUnit: "m", purchaseUnit: "rouleau", purchaseUnitSize: 50 },
      { name: "Gants de protection", category: "petroleum", unitType: "pair", baseUnit: "pair", sellingUnit: "pair", purchaseUnit: "carton", purchaseUnitSize: 100 },
      { name: "Lunettes de sécurité", category: "petroleum", unitType: "piece", baseUnit: "piece", sellingUnit: "piece", purchaseUnit: "carton", purchaseUnitSize: 30 },
    ]
  },
];

// Export as a module
export { BURUNDI_TEMPLATES };